import { useState } from "react";
import { useNavigate, Link } from "react-router-dom";
import { verifyResetCode } from "./services/api";
import "./auth-v2.css";

export default function VerifyCodeV2() {
  const [code,setCode]=useState(""); const [message,setMessage]=useState(""); const [loading,setLoading]=useState(false);
  const navigate=useNavigate(); const email=sessionStorage.getItem("resetEmail");
  const submit=async(e)=>{e.preventDefault();setMessage("");if(!email)return setMessage("Your recovery session has expired. Please start again.");if(code.length!==6)return setMessage("Enter the 6-digit verification code.");try{setLoading(true);const data=await verifyResetCode(email,code);sessionStorage.setItem("verificationResetToken",data.resetToken);setMessage("Code verified. You can now choose a new password.");setTimeout(()=>navigate("/reset-password"),500);}catch(error){setMessage(error.message||"Invalid verification code.");}finally{setLoading(false);}};
  return <main className="auth-page"><section className="auth-brand-panel"><div className="auth-brand"><div className="auth-logo">E</div><div><strong>Expenso</strong><span>Business Manager</span></div></div><div className="auth-brand-content"><span className="auth-eyebrow">VERIFY IDENTITY</span><h1>One more<br/><em>step.</em></h1><p>Enter the six-digit code from your Expenso recovery email.</p><div className="auth-trust-grid"><div><i className="fa-solid fa-clock"/><span><b>15-minute window</b><small>Codes expire automatically</small></span></div></div></div><small className="auth-footer">© 2026 Expenso · Secure account recovery</small></section><section className="auth-form-panel"><div className="auth-card"><div className="auth-card-top"><span className="auth-mini-label">VERIFICATION CODE</span><h2>Confirm it’s you</h2><p>Enter the code sent to your email.</p></div>{message&&<div className="auth-alert" role="status"><i className="fa-solid fa-circle-info"/>{message}</div>}<form onSubmit={submit}><div className="auth-field"><label htmlFor="recovery-code">6-digit code</label><div className="auth-input"><i className="fa-solid fa-key"/><input id="recovery-code" name="code" inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,""))} placeholder="000000" required/></div></div><button className="auth-submit" disabled={loading}>{loading?"Verifying…":"Verify code"}</button></form><div className="auth-divider"><span>NEED A NEW CODE?</span></div><Link className="auth-secondary" to="/forgot-password">Start again</Link></div></section></main>;
}
